# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_left_1', models.BooleanField(default=False)),
                ('upper_left_2', models.BooleanField(default=False)),
                ('upper_left_3', models.BooleanField(default=False)),
                ('upper_left_4', models.BooleanField(default=False)),
                ('upper_left_5', models.BooleanField(default=False)),
                ('upper_left_6', models.BooleanField(default=False)),
                ('upper_left_7', models.BooleanField(default=False)),
                ('upper_right_1', models.BooleanField(default=False)),
                ('upper_right_2', models.BooleanField(default=False)),
                ('upper_right_3', models.BooleanField(default=False)),
                ('upper_right_4', models.BooleanField(default=False)),
                ('upper_right_5', models.BooleanField(default=False)),
                ('upper_right_6', models.BooleanField(default=False)),
                ('upper_right_7', models.BooleanField(default=False)),
                ('upper_colet_from', models.CharField(choices=[('L1', 'LEFT 1'), ('L2', 'LEFT 2'), ('L3', 'LEFT 3'), ('L4', 'LEFT 4'), ('L5', 'LEFT 5'), ('L6', 'LEFT 6'), ('L7', 'LEFT 7')], max_length=2)),
                ('upper_colet_to', models.CharField(choices=[('R1', 'RIGHT 1'), ('R2', 'RIGHT 2'), ('R3', 'RIGHT 3'), ('R4', 'RIGHT 4'), ('R5', 'RIGHT 5'), ('R6', 'RIGHT 6'), ('R7', 'RIGHT 7')], max_length=2)),
                ('lower_left_1', models.BooleanField(default=False)),
                ('lower_left_2', models.BooleanField(default=False)),
                ('lower_left_3', models.BooleanField(default=False)),
                ('lower_left_4', models.BooleanField(default=False)),
                ('lower_left_5', models.BooleanField(default=False)),
                ('lower_left_6', models.BooleanField(default=False)),
                ('lower_left_7', models.BooleanField(default=False)),
                ('lower_right_1', models.BooleanField(default=False)),
                ('lower_right_2', models.BooleanField(default=False)),
                ('lower_right_3', models.BooleanField(default=False)),
                ('lower_right_4', models.BooleanField(default=False)),
                ('lower_right_5', models.BooleanField(default=False)),
                ('lower_right_6', models.BooleanField(default=False)),
                ('lower_right_7', models.BooleanField(default=False)),
                ('lower_colet_from', models.CharField(choices=[('L1', 'LEFT 1'), ('L2', 'LEFT 2'), ('L3', 'LEFT 3'), ('L4', 'LEFT 4'), ('L5', 'LEFT 5'), ('L6', 'LEFT 6'), ('L7', 'LEFT 7')], max_length=2)),
                ('lower_colet_to', models.CharField(choices=[('R1', 'RIGHT 1'), ('R2', 'RIGHT 2'), ('R3', 'RIGHT 3'), ('R4', 'RIGHT 4'), ('R5', 'RIGHT 5'), ('R6', 'RIGHT 6'), ('R7', 'RIGHT 7')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectcases.Patient'),
        ),
    ]
