# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectcases', '0002_add_dummy_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lower_colet_from',
            field=models.CharField(blank=True, choices=[('L1', 'LEFT 1'), ('L2', 'LEFT 2'), ('L3', 'LEFT 3'), ('L4', 'LEFT 4'), ('L5', 'LEFT 5'), ('L6', 'LEFT 6'), ('L7', 'LEFT 7')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lower_colet_to',
            field=models.CharField(blank=True, choices=[('R1', 'RIGHT 1'), ('R2', 'RIGHT 2'), ('R3', 'RIGHT 3'), ('R4', 'RIGHT 4'), ('R5', 'RIGHT 5'), ('R6', 'RIGHT 6'), ('R7', 'RIGHT 7')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='upper_colet_from',
            field=models.CharField(blank=True, choices=[('L1', 'LEFT 1'), ('L2', 'LEFT 2'), ('L3', 'LEFT 3'), ('L4', 'LEFT 4'), ('L5', 'LEFT 5'), ('L6', 'LEFT 6'), ('L7', 'LEFT 7')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='upper_colet_to',
            field=models.CharField(blank=True, choices=[('R1', 'RIGHT 1'), ('R2', 'RIGHT 2'), ('R3', 'RIGHT 3'), ('R4', 'RIGHT 4'), ('R5', 'RIGHT 5'), ('R6', 'RIGHT 6'), ('R7', 'RIGHT 7')], max_length=2, null=True),
        ),
    ]
