# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectcases', '0003_auto_20170715_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
