# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectcases', '0006_auto_20170716_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='baseplate',
            field=models.CharField(choices=[('AC', 'Acrylic'), ('HI', 'High Impact Acrylic')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='device',
            name='teeth',
            field=models.CharField(choices=[('01', 'Standard'), ('02', 'High Quality')], default='01', max_length=2),
        ),
    ]
