# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectcases', '0007_auto_20170716_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(choices=[(1, b'Awaiting impression'), (2, b'Impression received'), (3, b'Processing in lab'), (4, b'Awaiting device'), (5, b'Device received')], default=1),
        ),
    ]
